id: I507F3ECF
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-10 00:33:42.541474
last_modified: 2023-02-10 00:33:42.541644
source_metadata:
  title: 'Nāgārjuna: Vigrahavyāvartanīvṛtti'
  language: zh
bases:
  52DA:
    base_file: 52DA.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
